Add method for returns the map with content of fields that the new row was filled
odoo-java/odoo-java-api pull request #13
Opened 2021-07-15 14:46 UTC by gpbonillas

-  Change the dependency version from 3.1.6 to 3.1.7 on pom file
-  Add public method for getting the field attribute that has the row content

2021-07-23 15:57 UTC, flotho reviewed
Hi, thanks for your proposal,
any chance to use the same pattern for indentation so that it won't turn the review process into a nightmare for later contributions and modifications?

2021-07-23 16:04 UTC, flotho requested changes
thanks for your proposal : 
* some changes are required to be merged please see my comments
* could you also precise what kind of use case you're dealing with this change and propose it on the readme
* could you also squash you commits once done

2021-07-23 16:04 UTC, flotho commented on src/main/java/com/odoojava/api/Row.java
> +	public HashMap<String, Object> getFieldsOpenERPResult() {
Please change the name of your methode and replace openrpresult by Odoo even if the variable is openerp.

2021-08-02 15:54 UTC, gpbonillas commented on src/main/java/com/odoojava/api/Context.java
> + *
Yes, I only added spaces for legibility, but there's no problem to use the same source/pattern.

2021-08-02 15:56 UTC, gpbonillas commented on src/main/java/com/odoojava/api/Row.java
> +	public HashMap<String, Object> getFieldsOpenERPResult() {
I will change it according to your suggestion and push the commit

2021-08-02 18:36 UTC, gpbonillas commented
> thanks for your proposal :
> 
> * some changes are required to be merged please see my comments
> * could you also precise what kind of use case you're dealing with this change and propose it on the readme
> * could you also squash you commits once done

-----
About the use case for **getFieldsOdoo** method:

I need to get fields and then save for tracking purposes when I create a new object.

2021-08-02 18:57 UTC, gpbonillas commented
> * propose

The README file was updated with the proposal.

2021-08-16 19:43 UTC, gpbonillas commented
> Hi @gpbonillas
> 
> I really appreciate your effort.
> I still have a pbm regarding spaces you use for src/main/java/com/odoojava/api/ObjectAdapter.java for example. All the file is given different from source so it's difficult for me to check everything.
> Could you please change your settings so that the space number still the same as the original one in the project?
> 
> Regards

Sorry!. I update the file, then merge. The changes are: https://github.com/odoo-java/odoo-java-api/pull/13/commits/22e9daa0f0419f1fd1e067240dd20ad3c0e6e33a

2021-08-16 21:14 UTC, merged